app:
  name: wlkg
  endpoint: https://fuseki.hfpo-kfpo.di.unito.it/wlkg/query
  namespace: 
    entities_type: 
      entità1:
        label: "person"
        type: "prov:Person" 
        color: "#FF5733"
      entità2:
        label: "publisher"
        type: "urb:Publisher"
        color: "#33C1FF"
      entità3:
        label: "book"
        type: "frbr:Expression"
        color: "#75FF33"
      entità4:
        label: "topic"
        type: "frbr:Subject"
        color: "#FF33A8"
      entità5:
        label: "country"
        type: "rdfs:Class"
        color: "#F3FF33"
  prefix: 
    urw: <http://purl.archive.org/urwriters#> 
  prefixes: |
    PREFIX urw: <http://purl.archive.org/urwriters#> 
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    PREFIX prov: <http://www.w3.org/ns/prov#>
    PREFIX urb: <http://purl.archive.org/urbooks#>
  template: "{'QuestionFocus': '', 'entities': {'work': [],'person': [], 'subject':[], 'publisher':[]}}"